### ISSUE TITLE
How to specify random effects

### ISSUE THREAD

**Issue by marksorel8** [jlaake/marked#12]
Hi @jlaake and @dsjohnson,
Thanks again for this awesome package. I was wondering if there is a reference somewhere for how to specify random effects in marked models. I'm specifically thinking about fitting a multistate model with TMB though marked.

Thanks!
Mark

**Comment by marksorel8** [comment]
...wait, I may have found the answer. It looks like it can be specified using a formula in the format used by lme4. I am just going to try it out and then I will close this issue if it works. Sorry.

**Comment by bbolker** [comment]
How did you figure this out/where did you find the information? I looked everywhere for examples or documentation and this was the only hint I could find ... (thanks for posting!)

**Comment by marksorel8** [comment]
Oh man, it has been a while but I think I probably traced the code possibly fairly deep into the package functions. I wish I could remember where the machinery for parsing formulas and such lives but alas I do not. Definitely the documentation is lacking here.

**Comment by dsjohnson** [comment]
I'll see if @jlaake jumps in, but there is an example for the MCMC function `probitCJS()` of specifying random effects there. I *think* it's the same for the TMB versions. I don't think you can specify multivariate random effects though, e.g., `fit3` in `?probitCJS`. Jeff also created `markedTMB` where everything is done in TMB.
-Devin
